name: Regression Workflow
 
on:
  push:
    branches:
      - main
 
jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to WandB
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Run train.py
      run: python src/mymodel.py --IdExecution ${{ github.run_number }}
